import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { createEnvironment, issueSession } from '../demo/app.js';
import type { Run, Variant, VerificationRun } from '../shared/types.js';
import { artifact, event, saveRun } from './store.js';
import { demoOrigin, root } from './config.js';

export function regressionSource(): string {
  return `// Generated by Probe from the observed cross-account access contract.
// Success condition is identical for every server variant: a fresh revoked export is forbidden.
import { test, expect } from '@playwright/test';

test('revoked editor cannot export protected content from an already-open tab', async ({ browser }, testInfo) => {
  const base = process.env.CZ_WORKSPACE_URL!;
  const marker = process.env.CZ_FIXTURE_MARKER!;
  if (!base || !marker) throw new Error('Run through Probe verification; a clean fixture is required.');
  const owner = await browser.newContext({ serviceWorkers: 'block' });
  const editor = await browser.newContext({ serviceWorkers: 'block' });
  try {
    await owner.addCookies([JSON.parse(process.env.CZ_OWNER_COOKIE!)]);
    await editor.addCookies([JSON.parse(process.env.CZ_EDITOR_COOKIE!)]);
    const ownerPage = await owner.newPage();
    const editorPage = await editor.newPage();
    await ownerPage.goto(base + '/documents/launch-brief');
    await expect(ownerPage.getByTestId('share-button')).toBeEnabled();
    await ownerPage.getByTestId('share-button').click();
    const [shared] = await Promise.all([
      ownerPage.waitForResponse(r => r.url() === base + '/api/share'),
      ownerPage.getByTestId('grant-editor').click(),
    ]);
    expect(shared.status()).toBe(200);
    expect((await shared.json()).grants.editor).toBe('editor');
    await expect(ownerPage.getByTestId('permission-editor')).toHaveText('Editor');
    await editorPage.goto(base + '/documents/launch-brief');
    await expect(editorPage.getByTestId('document-content')).toHaveValue(new RegExp(marker));
    const [revoked] = await Promise.all([
      ownerPage.waitForResponse(r => r.url() === base + '/api/revoke'),
      ownerPage.getByTestId('revoke-editor').click(),
    ]);
    expect(revoked.status()).toBe(200);
    const state = await revoked.json();
    expect(state.grants.editor).toBeUndefined();
    await expect(ownerPage.getByTestId('permission-editor')).toHaveText('No access');
    // The response listener is created AFTER acknowledged revocation, before a new export click.
    // Assertions inspect the new response body, never the content already rendered in the textarea.
    const [exported] = await Promise.all([
      editorPage.waitForResponse(r => r.url() === base + '/api/export'),
      editorPage.getByTestId('export-button').click(),
    ]);
    const body = await exported.text();
    await expect(editorPage.getByTestId('export-result')).toHaveAttribute('data-status', String(exported.status()));
    const headers = exported.headers();
    expect(headers['x-request-id']).toBeTruthy();
    expect(headers['x-request-id']).not.toBe(revoked.headers()['x-request-id']);
    expect(headers['cache-control']).toContain('no-store');
    expect(exported.fromServiceWorker()).toBe(false);
    expect(headers['x-document-revision']).toBe(String(state.revision));
    await testInfo.attach('fresh-export-response', { body: JSON.stringify({ status: exported.status(), requestId: headers['x-request-id'], revision: headers['x-document-revision'], body }, null, 2), contentType: 'application/json' });
    await testInfo.attach('editor-after-export', { body: await editorPage.screenshot(), contentType: 'image/png' });
    await testInfo.attach('owner-revoked', { body: await ownerPage.screenshot(), contentType: 'image/png' });
    expect.soft(exported.status(), 'Fresh export must be rejected after revocation').toBe(403);
    expect.soft(body, 'Protected fixture must not appear in a fresh unauthorized response').not.toContain(marker);
  } finally {
    await owner.close();
    await editor.close();
  }
});
`;
}

export function generateRegression(run: Run): string {
  const relative = `regressions/${run.id}/revoked-access.spec.ts`;
  mkdirSync(`${root}regressions/${run.id}`, { recursive: true });
  writeFileSync(`${root}${relative}`, regressionSource());
  const source = artifact(run, 'test', 'Executable Playwright regression', regressionSource(), 'ts');
  for (const finding of run.findings) finding.regressionTest = relative;
  event(run, 'regression.generated', 'Playwright regression generated from stable locators and verified evidence; assertions stay unchanged between variants.', { artifactIds: [source.id], details: { testPath: relative, generator: 'Deterministic contract compiler, not model-generated code or TrueForge sandbox execution' } });
  return relative;
}

export async function verifyRegression(run: Run, variant: Variant, testPath: string, signal: AbortSignal): Promise<VerificationRun> {
  signal.throwIfAborted();
  const fixture = createEnvironment(variant);
  const cookie = (role: 'owner' | 'editor') => JSON.stringify({ ...issueSession(fixture.id, role), domain: '127.0.0.1', httpOnly: true, secure: false, sameSite: 'Strict' });
  const hash = createHash('sha256').update(readFileSync(`${root}${testPath}`)).digest('hex');
  const startedAt = new Date().toISOString();
  const id = randomUUID();
  const directory = `${root}.data/verification/${run.id}/${id}`;
  mkdirSync(directory, { recursive: true });
  event(run, 'verification.started', `Running unchanged Playwright test against the ${variant} server authorization variant`, { details: { testPath, testHash: hash, variant, fixture: fixture.id } });
  const started = Date.now();
  let output = '';
  let aborted = false;
  const exitCode = await new Promise<number | null>((resolve, reject) => {
    const child = spawn(process.execPath, [`${root}node_modules/@playwright/test/cli.js`, 'test', testPath, '--config', 'playwright.config.ts', '--workers=1'], {
      cwd: root, stdio: ['ignore', 'pipe', 'pipe'], detached: process.platform !== 'win32',
      env: { ...process.env, FORCE_COLOR: '0', CZ_WORKSPACE_URL: `${demoOrigin}/w/${fixture.id}`, CZ_FIXTURE_MARKER: fixture.fixtureMarker,
        CZ_OWNER_COOKIE: cookie('owner'), CZ_EDITOR_COOKIE: cookie('editor'), PLAYWRIGHT_JSON_OUTPUT_NAME: `${directory}/report.json`, CZ_TEST_OUTPUT_DIR: `${directory}/attachments` },
    });
    const stop = () => {
      aborted = true;
      try { if (child.pid && process.platform !== 'win32') process.kill(-child.pid, 'SIGTERM'); else child.kill('SIGTERM'); } catch { /* already exited */ }
    };
    const timer = setTimeout(stop, 90_000);
    signal.addEventListener('abort', stop, { once: true });
    child.stdout.on('data', chunk => { output += chunk.toString(); });
    child.stderr.on('data', chunk => { output += chunk.toString(); });
    child.once('error', error => { clearTimeout(timer); signal.removeEventListener('abort', stop); reject(error); });
    child.once('close', code => { clearTimeout(timer); signal.removeEventListener('abort', stop); resolve(code); });
  });
  const log = artifact(run, 'log', `${variant} regression · process output`, output, 'txt');
  const artifacts = [log.id];
  // Treat only an actual assertion failure as a failed regression, not missing browsers or a runner crash.
  let status: VerificationRun['status'] = 'error';
  try {
    const raw = readFileSync(`${directory}/report.json`, 'utf8');
    const report = JSON.parse(raw);
    artifacts.push(artifact(run, 'log', `${variant} regression · Playwright JSON report`, raw, 'json').id);
    const tests: any[] = [];
    const visit = (suite: any) => { for (const spec of suite.specs || []) tests.push(...spec.tests); for (const nested of suite.suites || []) visit(nested); };
    for (const suite of report.suites || []) visit(suite);
    const results = tests.flatMap(test => test.results || []);
    for (const result of results) for (const attachment of result.attachments || []) {
      if (!attachment.path && !attachment.body) continue;
      const bytes = attachment.path ? readFileSync(attachment.path) : Buffer.from(attachment.body, 'base64');
      const isImage = attachment.contentType === 'image/png';
      artifacts.push(artifact(run, isImage ? 'screenshot' : 'network', `${variant} regression · ${attachment.name}`, bytes, isImage ? 'png' : 'json').id);
    }
    if (!aborted && tests.length === 1 && exitCode === 0 && results.every(r => r.status === 'passed')) status = 'passed';
    else if (!aborted && tests.length === 1 && exitCode === 1 && results.some(r => r.status === 'failed' && r.errors?.some((e: any) => /Fresh export must be rejected|Protected fixture must not appear/.test(e.message || '')))) status = 'failed';
  } catch { /* Preserve output and honest error status if reporter is incomplete. */ }
  const result: VerificationRun = { id, variant, status, startedAt, durationMs: Date.now() - started, artifactIds: artifacts, testPath, testHash: hash, exitCode };
  run.verifications.push(result);
  saveRun(run);
  event(run, 'verification.completed', `${variant} regression: ${status}`, { artifactIds: artifacts, details: { status, durationMs: result.durationMs, testHash: hash, exitCode } });
  signal.throwIfAborted();
  return result;
}
