// Generated by CUSTOMER ZERO from the observed cross-account access contract.
// Success condition is identical for every server variant: a fresh revoked export is forbidden.
import { test, expect } from '@playwright/test';

test('revoked editor cannot export protected content from an already-open tab', async ({ browser }, testInfo) => {
  const base = process.env.CZ_WORKSPACE_URL!;
  const marker = process.env.CZ_FIXTURE_MARKER!;
  if (!base || !marker) throw new Error('Run through CUSTOMER ZERO verification; a clean fixture is required.');
  const owner = await browser.newContext({ serviceWorkers: 'block' });
  const editor = await browser.newContext({ serviceWorkers: 'block' });
  try {
    await owner.addCookies([JSON.parse(process.env.CZ_OWNER_COOKIE!)]);
    await editor.addCookies([JSON.parse(process.env.CZ_EDITOR_COOKIE!)]);
    const ownerPage = await owner.newPage();
    const editorPage = await editor.newPage();
    await ownerPage.goto(base + '/documents/launch-brief');
    await expect(ownerPage.getByTestId('share-button')).toBeEnabled();
    await ownerPage.getByTestId('share-button').click();
    const [shared] = await Promise.all([
      ownerPage.waitForResponse(r => r.url() === base + '/api/share'),
      ownerPage.getByTestId('grant-editor').click(),
    ]);
    expect(shared.status()).toBe(200);
    expect((await shared.json()).grants.editor).toBe('editor');
    await expect(ownerPage.getByTestId('permission-editor')).toHaveText('Editor');
    await editorPage.goto(base + '/documents/launch-brief');
    await expect(editorPage.getByTestId('document-content')).toHaveValue(new RegExp(marker));
    const [revoked] = await Promise.all([
      ownerPage.waitForResponse(r => r.url() === base + '/api/revoke'),
      ownerPage.getByTestId('revoke-editor').click(),
    ]);
    expect(revoked.status()).toBe(200);
    const state = await revoked.json();
    expect(state.grants.editor).toBeUndefined();
    await expect(ownerPage.getByTestId('permission-editor')).toHaveText('No access');
    // The response listener is created AFTER acknowledged revocation, before a new export click.
    // Assertions inspect the new response body, never the content already rendered in the textarea.
    const [exported] = await Promise.all([
      editorPage.waitForResponse(r => r.url() === base + '/api/export'),
      editorPage.getByTestId('export-button').click(),
    ]);
    const body = await exported.text();
    await expect(editorPage.getByTestId('export-result')).toHaveAttribute('data-status', String(exported.status()));
    const headers = exported.headers();
    expect(headers['x-request-id']).toBeTruthy();
    expect(headers['x-request-id']).not.toBe(revoked.headers()['x-request-id']);
    expect(headers['cache-control']).toContain('no-store');
    expect(exported.fromServiceWorker()).toBe(false);
    expect(headers['x-document-revision']).toBe(String(state.revision));
    await testInfo.attach('fresh-export-response', { body: JSON.stringify({ status: exported.status(), requestId: headers['x-request-id'], revision: headers['x-document-revision'], body }, null, 2), contentType: 'application/json' });
    await testInfo.attach('editor-after-export', { body: await editorPage.screenshot(), contentType: 'image/png' });
    await testInfo.attach('owner-revoked', { body: await ownerPage.screenshot(), contentType: 'image/png' });
    expect.soft(exported.status(), 'Fresh export must be rejected after revocation').toBe(403);
    expect.soft(body, 'Protected fixture must not appear in a fresh unauthorized response').not.toContain(marker);
  } finally {
    await owner.close();
    await editor.close();
  }
});
